name: Arweave Sync

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install and Run Protocol Sync
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_TITLE: Notification
          REPO_DESCRIPTION: ''
          WALLET: ${{ secrets.ARWEAVE_WALLET }}
        run: |
          echo "$WALLET" > arweave-wallet-key.json
          npx @protocol.land/sync --wallet arweave-wallet-key.json
